sonar.projectKey=python-security-demo
sonar.organization=699b11af4ff1b0077ad28a8a2380000929b3991d

sonar.projectName=Python Security Demo
sonar.sources=.
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
